coverage:
  status:
    project:
      default:
        target: auto
        threshold: 80%
        base: auto
        flags:
          - unit
        paths:
          - "src"
        branches:
          - master
        if_not_found: success
        if_ci_failed: error
        informational: False
        only_pulls: false
ignore:
  - "src/java/com/Main.*"