language: java
sudo: required
os: linux
dist: trusty

branches:
  only:
    - master
env:
  global:
    - PROJECT_VERSION="default"
  - tf_version=0.12.19 tf_init_cli_options="-input=false" tf_validation_cli_options="" tf_plan_cli_options="-lock=false -input=false" tf_apply_cli_options="-auto-approve -input=false"



jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
  - unzip terraform_"$tf_version"_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_"$tf_version"_linux_amd64.zip

script:
  - mvn compile
  - mvn test
  - mvn cobertura:cobertura

after_success:
  - mvn site
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
  - dockerbuild/update.sh
  - PROJECT_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
  - cp gen_dockerfile/files/Dockerfile ${HOME}/;
  - cp target/devops-${PROJECT_VERSION}-jar-with-dependencies.jar ${HOME}/;

before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin;


deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: target/site
    github_token: $GH_TOKEN
    keep_history: true
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    script: bash docker_push.sh
    keep_history: true
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    keep_history: true
    script: bash git_push.sh
    on:
      branch: master

  - provider: releases
    api_key:
      secure: $GH_TOKEN
    file: ${HOME}/devops-${PROJECT_VERSION}-jar-with-dependencies.jar
    skip_cleanup: true
    on:
      tags: true

