language: java
sudo: required
os: linux
dist: trusty

branches:
  only:
    - master

jdk:
  - oraclejdk8

services:
  - docker

script:
  - mvn compile
  - mvn test
  - mvn cobertura:cobertura

after_success:
  - mvn site
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

before_deploy:
  - dockerbuild/update.sh
  - ls dockerbuild

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: target/site
    github_token: $GH_TOKEN
    keep_history: true
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    script: bash docker_push.sh
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    script: bash git_push.sh
    on:
      branch: master

