language: java
sudo: required
os: linux
dist: trusty

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/
env:
  global:
    - PROJECT_VERSION="default"

jdk:
  - oraclejdk8

services:
  - docker

script:
  - mvn compile
  - mvn test
  - mvn cobertura:cobertura

after_success:
  - mvn site
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
  - dockerbuild/update.sh
  - PROJECT_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
  - cp gen_dockerfile/files/Dockerfile ${HOME}/;
  - cp target/devops-${PROJECT_VERSION}-jar-with-dependencies.jar ${HOME}/;

before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin;

deploy:
  - provider: releases
    skip_cleanup: true
    keep_history: true
    overwrite: true
    api_key:
      secure: $GITHUB_OAUTH_TOKEN
    file: ${HOME}/devops-${PROJECT_VERSION}-jar-with-dependencies.jar
    on:
      tags: true
      repo: A-Julien/devops

  - provider: pages
    skip_cleanup: true
    local_dir: target/site
    github_token: $GH_TOKEN
    keep_history: true
    on:
      tags: false
      branch: master

  - provider: script
    skip_cleanup: true
    script: bash docker_push.sh
    keep_history: true
    on:
      tags: false
      branch: master

  - provider: script
    skip_cleanup: true
    keep_history: true
    script: bash git_push.sh
    on:
      tags: false
      branch: master