language: java
sudo: required
os: linux
dist: trusty
branches:
  only:
    - master
    - "/^\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    - PROJECT_VERSION="default"
    - secure: jrUx8qTuAajdkbVda6288nfBgRQ21qfye3UrAqoRWxASzzH8NEaw6jAz/1ysxE0B+XBmlASq1IyvKlyFLBqGLWt//IMK+jTKY2gAfZuw//0KWWJI8RXwSqvcHx0D+RWtA1u6t71uIrSgerBclEgB0Nhtygffu9JRPxfh9Tr7JX3ojrN8eLj+6nX1/FlMvWpPEeCIDexP4mKgTBFtIGZEJAfJ86l7vN/onGDBmWnKSdrNy/SEV2vrD+NpKj3HbDhcm9AXb0obHyOdbreTRt4SaNzGg5494n6IziSx39yw/OSgsMd1SvNHLtOJ3lyib5dJFInkSTL0FUx4EnbhsB7jqs5b2437bJEEO5/ZeDlsABpclRKiJk5owTuPSfZH8DS04zfp2chC70igCU44BTL8DmZdu0fvbW0kyYY/LFO2+LoxYXgPOz7YSjuZJLO9PUzC5+7NgadjLiziNDss6uUz8yqUAjR1ReQPHP2h6N8sFc3ecGkXpUVJyrU6EgeJtnspi3905G3/rW1pkLE8ahn9D5hjOMlRU4YblrbwEo3uTUGK+vq13wi30efLCl6msZFkOs7J/E/NQLcRf30h3kMs+03XMmXHCxiv+J6qmCLwZdhnbA/In7hSbe96l0TohNBkqn0gxfwx2LBPaPtWfVav9DwENjcmE5IlgWsgCIm6GEI=
jdk:
  - oraclejdk8
services:
  - docker
script:
  - mvn compile
  - mvn test
  - mvn cobertura:cobertura
after_success:
  - mvn site
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
  - dockerbuild/update.sh
  - PROJECT_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}'
    --non-recursive exec:exec)
  - cp gen_dockerfile/files/Dockerfile ${HOME}/;
  - cp target/devops-${PROJECT_VERSION}-jar-with-dependencies.jar ${HOME}/;
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin;

deploy:
  - provider: releases
    skip_cleanup: true
    keep_history: true
    overwrite: true
    api_key: "$GITHUB_OAUTH_TOKEN"
    file: "${HOME}/devops-${PROJECT_VERSION}-jar-with-dependencies.jar"
    on:
      tags: true
      repo: A-Julien/devops
  - provider: pages
    skip_cleanup: true
    local_dir: target/site
    github_token: "$GH_TOKEN"
    keep_history: true
    on:
      tags: false
      branch: master
  - provider: script
    skip_cleanup: true
    script: bash docker_push.sh
    keep_history: true
    on:
      tags: false
      branch: master
  - provider: script
    skip_cleanup: true
    keep_history: true
    script: bash git_push.sh
    on:
      tags: false
      branch: master
