language: java
sudo: required
os: linux
dist: trusty

branches:
  only:
    - master

jdk:
  - oraclejdk8

services:
  - docker

script:
  - mvn compile
  - mvn test
  - mvn cobertura:cobertura

after_success:
  - mvn site
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
  - dockerbuild/update.sh
  - PROJECT_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
  - ln target/devops-${PROJECT_VERSION}-jar-with-dependencies.jar gen_dockerfile/files/

before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
  - ls dockerbuild

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: target/site
    github_token: $GH_TOKEN
    keep_history: true
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    script: bash docker_push.sh
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    script: bash git_push.sh
    on:
      branch: master

