language: java
sudo: required
os: linux
dist: trusty

branches:
  only:
    - master

jdk:
  - oraclejdk8

services:
  - docker

script:
  - mvn cobertura:cobertura

after_success:
  - chmod +x push.sh
  - chmod +x pushdoc.sh
  - mvn site
  - ./pushdoc.sh
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN


before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - dockerbuild/update.sh

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master